apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
  labels:
    app: myapp-deployment
    type: front-end

spec: 
  template: 
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: hello-world
          image: hello-world

  replicas: 3
  selector:
    matchLabels:
      app: myapp
    